### ISSUE TITLE
About Menu Crash

### ISSUE THREAD

**Issue by ThatSportsGamer** [thatzacdavis/Extra-Life-Helper-.NET#1]
Extra-Life-Helper-.NET-master\Extra Life Helper .NET\bin\Debug\Extra_Life_Helper.NET

If you click on "About" the new window pops up with the About info. If you close it with the X or the "Close" button, the next time you click "About" the program crashes. 

![screenshot 45](https://cloud.githubusercontent.com/assets/14823321/10076897/c0c6ee1c-62ab-11e5-9a7f-a2436075dfc5.jpg)

**Comment by thatzacdavis** [comment]
Issue also occurs for Settings menu.

This was caused by constructing the form objects on the original form load, and not when the buttons were clicked.
